[package]
name = "JoystickFullRust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
steamy_base = { path = "/home/user/RustroverProjects/steamy_base" }
#rusb = "0.9"
#gilrs = "0.10"
kanal = "0.1.0-pre8"
#crossbeam-channel = "0.5"
ahash = { version = "0.8", features = ["serde"] }
bytes = "1.6"
color-eyre = "0.6"
lazy_static = "1.4"
validator = "0.18"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
trait-set = "0.3"
duplicate = "1.0"
strum = { version = "0.26", features = ["derive"] }
strum_macros = "0.26"
regex = "1.10"
env_logger = "0.11"
log = "0.4"
[target.'cfg(target_os = "windows")'.dependencies]
enigo = "0.2"
[target.'cfg(target_os = "linux")'.dependencies]
mouse-keyboard-input = { git = "https://github.com/positiveway/mouse-keyboard-input", branch = "main" }
