[package]
name = "JoystickFullRust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.6.2"
lazy_static="1.4.0"
validator="0.16.1"
gilrs = "0.10.4"
mouse-keyboard-input = { git = "https://github.com/positiveway/mouse-keyboard-input", branch = "main" }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
toml = "0.8.9"
trait-set = "0.3.0"
duplicate = "1.0.0"
strum = { version = "0.26.1", features = ["derive"] }
strum_macros = "0.26.1"
regex = "1.10.3"
crossbeam-channel = "0.5.11"
env_logger = "0.11.1"
log = "0.4.20"