debug = false
buttons_layout = "gaming"
typing_layout = "typing"
triggers_threshold_pct = 30
mouse_speed = 400
scroll_speed = 600
horizontal_threshold_pct = 35
[finger_rotation]
use_rotation = true
left_pad = 8
right_pad = 8
stick = -10
[jitter_threshold]
left_pad = 0.02
right_pad = 0.01
stick = 0.0