[Debugging]
is_debug = false
use_steamy = true
use_raw_input = false
always_press = false
main_as_thread = false
[GradualMove]
mouse = true
scroll = true
[General]
steamy_channel_size = 100
commands_channel_size = 100
steamy_read_interrupt_interval = 0
input_raw_refresh_interval = 500
input_buffer_refresh_interval = 2
mouse_refresh_interval = 1
[Layouts]
#buttons_layout = "desktop"
buttons_layout = "raft"
#buttons_layout = "wmd"
typing_layout = "typing"
