buttons_layout="gaming"
typing_layout="typing"
finger_rotation=15
triggers_threshold_pct=30
mouse_speed = 400
scroll_speed = 600
horizontal_threshold_pct = 35
[jitter_threshold]
left_pad = 0.02
right_pad = 0.01
stick = 0.0