Layouts:
  #  buttons_layout: "desktop"
  buttons_layout: "raft"
  # buttons_layout: "risk"
  #  buttons_layout: "wmd"
  #  buttons_layout: "valheim"
  #  buttons_layout: "satisfactory"

  typing_layout: "typing"
General:
  steamy_channel_size: 100
  commands_channel_size: 100
  steamy_read_interrupt_interval: 0
  input_raw_refresh_interval: 500
  input_buffer_refresh_interval: 2
  mouse_refresh_interval: 1

is_left_pad_bytes_dump: false
