[Debugging]
is_debug = false
use_steamy = true
use_raw_input = true
always_press = false
main_as_thread = true
[Layouts]
#buttons_layout = "desktop"
buttons_layout = "raft"
#buttons_layout = "wmd"
typing_layout = "typing"
