[ButtonsLayout]
BtnUp_SideR = ["KEY_UP"]
BtnRight_SideR = ["KEY_RIGHT"]
BtnDown_SideR = ["KEY_DOWN"]
BtnLeft_SideR = ["KEY_LEFT"]

BtnUp_SideL = ["KEY_SPACE"]
BtnRight_SideL = ["KEY_F2"]
BtnDown_SideL = ["KEY_F11"]
BtnLeft_SideL = ["KEY_F4"]

Wing_SideL = ["MOUSE_MIDDLE"]
Wing_SideR = ["KEY_ENTER"]

LowerTriggerAsBtn_SideL = ["MOUSE_RIGHT"]
LowerTriggerAsBtn_SideR = ["MOUSE_LEFT"]

UpperTrigger_SideL = ["KEY_LEFTCTRL", "KEY_Z"]
UpperTrigger_SideR = ["KEY_LEFTCTRL", "KEY_LEFTSHIFT", "KEY_Z"]

# Causes instability
#PadAsBtn_SideL = ["KEY_LEFTCTRL", "KEY_X"]
#PadAsBtn_SideR = ["KEY_LEFTCTRL", "KEY_V"]
#StickAsBtn = ["KEY_LEFTCTRL", "KEY_C"]

ExtraBtn_SideL = ["KEY_ESC"]
ExtraBtnCentral = ["RESET_BTN"]
ExtraBtn_SideR = ["SWITCH_MODE_BTN"]

#PadUp_SideL = ["PadUp_SideL"]
#PadDown_SideL = ["PadDown_SideL"]
#PadLeft_SideL = ["PadLeft_SideL"]
#PadRight_SideL = ["PadRight_SideL"]
#PadUp_SideR = ["PadUp_SideR"]
#PadDown_SideR = ["PadDown_SideR"]
#PadLeft_SideR = ["PadLeft_SideR"]
#PadRight_SideR = ["PadRight_SideR"]

[General]
gaming_mode = false
repeat_keys = false
triggers_threshold_pct = 30
mouse_speed = 400
steamy_use_left_pad = true
[Scroll]
speed = 600
horizontal_threshold = 0.06
[JitterThreshold]
left_pad = 0.01
right_pad = 0.01
stick = 0.01
[Stick]
diagonal_zones = false
zone_range = 22
start_threshold_pct = 30
[AxisCorrection]
use_correction = true
[AxisCorrection.left_pad]
x = 2000
y = 3000
[AxisCorrection.right_pad]
x = 1000
y = 3000
[AxisCorrection.stick]
x = 0
y = 0
[FingerRotation]
use_rotation = false
left_pad = -20
right_pad = 8
stick = -8
