gaming_mode = false
#BtnUp_SideL = "BtnUp_SideL"
#BtnDown_SideL = "BtnDown_SideL"
#BtnLeft_SideL = "BtnLeft_SideL"
#BtnRight_SideL = "BtnRight_SideL"
BtnUp_SideR = "KEY_UP"
BtnDown_SideR = "KEY_DOWN"
BtnLeft_SideR = "KEY_LEFT"
BtnRight_SideR = "KEY_RIGHT"
Wing_SideL = "MOUSE_MIDDLE"
Wing_SideR = "KEY_ENTER"
LowerTriggerAsBtn_SideL = "MOUSE_RIGHT"
LowerTriggerAsBtn_SideR = "MOUSE_LEFT"
UpperTrigger_SideL = "KEY_UNDO"
UpperTrigger_SideR = "KEY_REDO"
PadAsBtn_SideL = "KEY_CUT"
PadAsBtn_SideR = "KEY_PASTE"
StickAsBtn = "KEY_COPY"
#PadUp_SideL = "PadUp_SideL"
#PadDown_SideL = "PadDown_SideL"
#PadLeft_SideL = "PadLeft_SideL"
#PadRight_SideL = "PadRight_SideL"
#PadUp_SideR = "PadUp_SideR"
#PadDown_SideR = "PadDown_SideR"
#PadLeft_SideR = "PadLeft_SideR"
#PadRight_SideR = "PadRight_SideR"
ExtraBtn_SideL = "KEY_ESC"
ExtraBtn_SideR = "SWITCH_MODE_BTN"
ExtraBtnCentral = "RESET_BTN"